apiVersion: v1
kind: Service
metadata:
  name: weather-backend-service
spec:
  selector:
    app: weather-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # You can change this to NodePort or LoadBalancer if required

---
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-service
spec:
  selector:
    app: weather-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # You can change this to NodePort if you don't need a LoadBalancer
