# Use official Node.js image
FROM node:22-slim

# Create app directory
WORKDIR /app

# Copy package.json and lock file
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Copy .env file
COPY .env .env

# Expose your app port
EXPOSE 5000

# Start the app
CMD ["npm", "start"]
